name: hng_stage3_app
description: Storekeeper App for HNG Mobile Track Stage 2
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"

flutter:
  uses-material-design: true

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  sqflite: ^2.2.8
  path_provider: ^2.0.14
  path: ^1.8.3
  image_picker: ^1.2.0
  provider: ^6.0.5
  flutter_slidable: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
